"use client";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Markdown } from "@/components/ui/markdown";
import {
  ArrowLeft,
  Printer,
  Link2,
  Check,
  Clock,
  FileText,
  MessageSquare,
} from "lucide-react";
import { useAppContext } from "@/components/providers/app-context";
import type { Report } from "@/lib/types";
import { useState, useCallback, useRef } from "react";

interface ReportViewProps {
  report: Report;
  onBack?: () => void;
}

export function ReportView({ report, onBack }: ReportViewProps) {
  const { setActiveView } = useAppContext();
  const [copied, setCopied] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  const handleBack = useCallback(() => {
    if (onBack) {
      onBack();
    } else {
      setActiveView("chat");
    }
  }, [onBack, setActiveView]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleCopyShareLink = useCallback(async () => {
    const url = `${window.location.origin}/api/reports/${report.id}?token=${report.shareToken}`;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for insecure contexts
      const input = document.createElement("input");
      input.value = url;
      document.body.appendChild(input);
      input.select();
      document.execCommand("copy");
      document.body.removeChild(input);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [report.id, report.shareToken]);

  const formattedDate = new Date(report.createdAt).toLocaleDateString(
    "en-US",
    {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }
  );

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* Toolbar — hidden in print */}
      <div className="report-toolbar flex items-center justify-between px-6 py-3 border-b shrink-0">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            className="gap-1.5"
            onClick={handleBack}
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Chat
          </Button>
          <Separator orientation="vertical" className="h-5" />
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-primary" />
            <span className="font-semibold text-sm">Report</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={handleCopyShareLink}
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-green-600" />
                Copied!
              </>
            ) : (
              <>
                <Link2 className="h-3.5 w-3.5" />
                Share Link
              </>
            )}
          </Button>
          <Button
            variant="default"
            size="sm"
            className="gap-1.5"
            onClick={handlePrint}
          >
            <Printer className="h-3.5 w-3.5" />
            Export PDF
          </Button>
        </div>
      </div>

      {/* Report body — scrollable, print-optimized */}
      <div className="flex-1 overflow-y-auto overscroll-contain">
        <div
          ref={printRef}
          className="report-printable max-w-3xl mx-auto px-8 py-10"
        >
          {/* Meta badges — hidden in print */}
          <div className="report-toolbar flex items-center gap-3 mb-6">
            <Badge variant="secondary" className="gap-1 text-xs">
              <Clock className="h-3 w-3" />
              {formattedDate}
            </Badge>
            <Badge variant="outline" className="gap-1 text-xs">
              <MessageSquare className="h-3 w-3" />
              {report.messageCount} messages
            </Badge>
          </div>

          {/* Markdown content */}
          <article className="report-article prose-report">
            <Markdown content={report.markdownContent} />
          </article>

          {/* Footer — visible in print */}
          <Separator className="mt-12 mb-4" />
          <p className="text-xs text-muted-foreground text-center">
            Generated by Tambo Lens • {formattedDate}
          </p>
        </div>
      </div>
    </div>
  );
}
